edits

diff --git a/.github/workflows/darshan-ldms-test_ci.yml b/.github/workflows/darshan-ldms-test_ci.yml
--- a/.github/workflows/darshan-ldms-test_ci.yml
+++ b/.github/workflows/darshan-ldms-test_ci.yml
@@ -104,14 +104,10 @@ jobs:
     #    cd darshan/darshan-util/pydarshan
     #    python -m pip install .
         #python -m pytest darshan-test/python_runtime_tests.py
-    - name: Test Preparation
+    - name: Test Preparation and Run
       run : |
         echo "---setting Darshan environment---"
-        echo $DARSHAN_INSTALL_PATH
         export DARSHAN_INSTALL_PATH=/opt/darshan_install
-        echo $DARSHAN_INSTALL_PATH
-        ls -ltr $DARSHAN_INSTALL_PATH
-        ls -ltr $DARSHAN_INSTALL_PATH/lib/
         export LD_PRELOAD=$DARSHAN_INSTALL_PATH/lib/libdarshan.so
         export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DARSHAN_INSTALL_PATH/lib
         export DARSHAN_INSTALL_PATH=$DARSHAN_INSTALL_PATH
@@ -134,7 +130,7 @@ jobs:
         export DXT_ENABLE_LDMS=
         export STDIO_ENABLE_LDMS=
         export HDF5_ENABLE_LDMS=
-        echo "---generating configuration file---"
+        echo "---generating ldmsd configuration file---"
         cat > stream-samp-4.3.3.conf << EOF
         load name=hello_sampler
         config name=hello_sampler producer=host1 instance=host1/hello_sampler stream=darshanConnector component_id=1
@@ -142,30 +138,62 @@ jobs:
         load name=stream_csv_store
         config name=stream_csv_store path=./streams/store container=csv stream=darshanConnector rolltype=3 rollover=500000
         EOF
-        echo "---starting ldmsd---"
+        echo "---Starting ldmsd---"
         ldmsd -x sock:10444 -c stream-samp-4.3.3.conf -l /tmp/stream-samp-4.3.3.log -v DEBUG
         cat /tmp/stream-samp-4.3.3.log
         ldms_ls -p 10444 -h localhost -v
-        echo "---Running Test Case---" 
+        echo "---Setting Test Case Variables---" 
+        export PROG=mpi-io-test
         export DARSHAN_INSTALL_PATH=/opt/darshan_install
         export DARSHAN_TMP=/tmp/darshan-ldms-test
         export DARSHAN_PLATFORM=cray-module-stria
         export DARSHAN_TESTDIR=$PWD/darshan/darshan-test/regression
-        export PROG=mpi-io-test
         export DARSHAN_LOGFILE=$DARSHAN_TMP/${PROG}.darshan
-        mkdir $DARSHAN_TMP
+        echo "---Checking TMP Path---"
+        if [ ! -x $DARSHAN_PATH/bin/darshan-dxt-parser ]; then
+                echo "Error: $DARSHAN_PATH doesn't contain a valid Darshan install." 1>&2
+                exit 1
+        fi
+        if [ ! -d $DARSHAN_TMP ]; then
+                mkdir -p $DARSHAN_TMP
+        fi
+        if [ ! -d $DARSHAN_TMP ]; then
+                echo "Error: unable to find or create $DARSHAN_TMP" 1>&2
+                exit 1
+        fi
+        if [ ! -w $DARSHAN_TMP ]; then
+                echo "Error: unable to write to $DARSHAN_TMP" 1>&2
+                exit 1
+        fi
         mpicc $DARSHAN_TESTDIR/test-cases/src/${PROG}.c -o $DARSHAN_TMP/${PROG}
-        ls -ltr $DARSHAN_TMP
         cd $DARSHAN_TMP
         ./${PROG} -f $DARSHAN_TMP/${PROG}.tmp.dat
-        $DARSHAN_INSTALL_PATH/bin/darshan-parser $DARSHAN_LOGFILE > $DARSHAN_TMP/${PROG}.darshan.txt
+        echo "---Parse Darshan file---"
+        $DARSHAN_INSTALL_PATH/bin/darshan-parser --all $DARSHAN_LOGFILE > $DARSHAN_TMP/${PROG}.darshan.txt
+        if [ $? -ne 0 ]; then
+                echo "Error: failed to parse ${DARSHAN_LOGFILE}" 1>&2
+                exit 1
+        fi
+        $DARSHAN_INSTALL_PATH/bin/darshan-dxt-parser --show-incomplete $DARSHAN_LOGFILE > $DARSHAN_TMP/${PROG}-dxt.darshan.txt
+        if [ $? -ne 0 ]; then
+                echo "Error: failed to parse ${DARSHAN_LOGFILE} for dxt tracing" 1>&2
+        exit 1
+        fi
     - name: Check Results
       run: |
-        echo "---Checking Output---"
+        echo "---Checking Results---"
+        export DARSHAN_TMP=/tmp/darshan-ldms-test
+        export PROG=mpi-io-test
         ls -ltr /tmp/stream-samp-4.3.3.log
+        ls -ltr streams/store/csv/
         cat /tmp/stream-samp-4.3.3.log
-        ls -ltr streams/store/
-        ls -ltr $DARSHAN_TMP
+        ls -ltr csv/
+        if [[ ! -f "$DARSHAN_TMP/${PROG}.darshan.txt" || ! -f "$DARSHAN_TMP/${PROG}-dxt.darshan.txt" ]]; then
+                echo "One of the darshan log files do not exist."
+                exit 1
+        fi
+        if [[ ! -f "streams/store/csv/darshanConnector*" ]]; then
+                echo "CSV file does not exist."
+                exit 1
+        fi        
         echo "DONE!"
-       
-   
